// Generated by tools/vo_edit.py from the voiceover alignment. Do not edit by hand.
window.TIMELINE = {
 "total": 140.67,
 "vo": "audio/vo.wav",
 "scenes": {
  "1": {
   "start": 0.0,
   "duration": 6.61,
   "cues": [
    {
     "start": 1.65,
     "end": 6.61,
     "text": "If you sell land on installments in Nigeria, you know this."
    }
   ],
   "words": [
    {
     "w": "if",
     "start": 1.75,
     "end": 1.99
    },
    {
     "w": "you",
     "start": 1.99,
     "end": 2.16
    },
    {
     "w": "sell",
     "start": 2.16,
     "end": 2.53
    },
    {
     "w": "land",
     "start": 2.53,
     "end": 3.17
    },
    {
     "w": "on",
     "start": 3.53,
     "end": 3.67
    },
    {
     "w": "installments",
     "start": 3.67,
     "end": 4.42
    },
    {
     "w": "in",
     "start": 4.42,
     "end": 4.51
    },
    {
     "w": "nigeria",
     "start": 4.51,
     "end": 5.11
    },
    {
     "w": "you",
     "start": 5.56,
     "end": 5.73
    },
    {
     "w": "know",
     "start": 5.73,
     "end": 5.89
    },
    {
     "w": "this",
     "start": 5.89,
     "end": 6.38
    }
   ]
  },
  "2": {
   "start": 6.61,
   "duration": 19.1,
   "cues": [
    {
     "start": 0.4,
     "end": 3.71,
     "text": "Most Nigerians buy land in installments,"
    },
    {
     "start": 3.71,
     "end": 7.3,
     "text": "paying over months or years."
    },
    {
     "start": 7.3,
     "end": 12.41,
     "text": "But the companies selling it still track everything by hand."
    },
    {
     "start": 12.41,
     "end": 14.08,
     "text": "Receipts on WhatsApp."
    },
    {
     "start": 14.08,
     "end": 15.93,
     "text": "Schedules in Excel."
    },
    {
     "start": 15.93,
     "end": 19.1,
     "text": "Commission arguments every month end."
    }
   ],
   "words": [
    {
     "w": "most",
     "start": 0.5,
     "end": 0.79
    },
    {
     "w": "nigerians",
     "start": 0.79,
     "end": 1.64
    },
    {
     "w": "buy",
     "start": 2.09,
     "end": 2.34
    },
    {
     "w": "land",
     "start": 2.34,
     "end": 2.8
    },
    {
     "w": "in",
     "start": 2.8,
     "end": 2.95
    },
    {
     "w": "installments",
     "start": 2.95,
     "end": 3.81
    },
    {
     "w": "paying",
     "start": 3.81,
     "end": 4.68
    },
    {
     "w": "over",
     "start": 4.68,
     "end": 5.11
    },
    {
     "w": "months",
     "start": 5.11,
     "end": 5.88
    },
    {
     "w": "or",
     "start": 5.99,
     "end": 6.17
    },
    {
     "w": "years",
     "start": 6.17,
     "end": 6.8
    },
    {
     "w": "but",
     "start": 7.4,
     "end": 7.67
    },
    {
     "w": "the",
     "start": 7.67,
     "end": 7.79
    },
    {
     "w": "companies",
     "start": 7.79,
     "end": 8.49
    },
    {
     "w": "selling",
     "start": 8.49,
     "end": 9.21
    },
    {
     "w": "it",
     "start": 9.28,
     "end": 9.87
    },
    {
     "w": "still",
     "start": 9.87,
     "end": 10.19
    },
    {
     "w": "track",
     "start": 10.19,
     "end": 10.94
    },
    {
     "w": "everything",
     "start": 10.94,
     "end": 11.42
    },
    {
     "w": "by",
     "start": 11.42,
     "end": 11.62
    },
    {
     "w": "hand",
     "start": 11.62,
     "end": 12.02
    },
    {
     "w": "receipts",
     "start": 12.51,
     "end": 12.93
    },
    {
     "w": "on",
     "start": 12.93,
     "end": 13.07
    },
    {
     "w": "whatsapp",
     "start": 13.07,
     "end": 13.72
    },
    {
     "w": "schedules",
     "start": 14.18,
     "end": 14.66
    },
    {
     "w": "in",
     "start": 14.66,
     "end": 14.8
    },
    {
     "w": "excel",
     "start": 14.8,
     "end": 15.43
    },
    {
     "w": "commission",
     "start": 16.03,
     "end": 16.47
    },
    {
     "w": "arguments",
     "start": 16.47,
     "end": 17.26
    },
    {
     "w": "every",
     "start": 17.56,
     "end": 17.87
    },
    {
     "w": "month",
     "start": 17.87,
     "end": 18.28
    },
    {
     "w": "end",
     "start": 18.28,
     "end": 18.7
    }
   ]
  },
  "3": {
   "start": 25.71,
   "duration": 3.65,
   "cues": [
    {
     "start": 1.8,
     "end": 3.65,
     "text": "So we built Terratrail."
    }
   ],
   "words": [
    {
     "w": "so",
     "start": 1.9,
     "end": 2.02
    },
    {
     "w": "we",
     "start": 2.02,
     "end": 2.15
    },
    {
     "w": "built",
     "start": 2.15,
     "end": 2.47
    },
    {
     "w": "terratrail",
     "start": 2.47,
     "end": 3.25
    }
   ]
  },
  "4": {
   "start": 29.36,
   "duration": 7.54,
   "cues": [
    {
     "start": 0.4,
     "end": 2.02,
     "text": "Create a subscription,"
    },
    {
     "start": 2.02,
     "end": 6.31,
     "text": "and every installment is scheduled for you."
    },
    {
     "start": 6.31,
     "end": 7.54,
     "text": "Automatically."
    }
   ],
   "words": [
    {
     "w": "create",
     "start": 0.5,
     "end": 0.74
    },
    {
     "w": "a",
     "start": 0.74,
     "end": 0.77
    },
    {
     "w": "subscription",
     "start": 0.77,
     "end": 1.67
    },
    {
     "w": "and",
     "start": 2.12,
     "end": 2.37
    },
    {
     "w": "every",
     "start": 2.37,
     "end": 2.59
    },
    {
     "w": "installment",
     "start": 2.59,
     "end": 3.55
    },
    {
     "w": "is",
     "start": 3.55,
     "end": 4.11
    },
    {
     "w": "scheduled",
     "start": 4.56,
     "end": 5.81
    },
    {
     "w": "for",
     "start": 5.81,
     "end": 6.01
    },
    {
     "w": "you",
     "start": 6.01,
     "end": 6.18
    },
    {
     "w": "automatically",
     "start": 6.41,
     "end": 7.25
    }
   ]
  },
  "5": {
   "start": 36.9,
   "duration": 5.55,
   "cues": [
    {
     "start": 0.4,
     "end": 1.72,
     "text": "Receipts come in."
    },
    {
     "start": 1.72,
     "end": 3.53,
     "text": "You approve them in one tap."
    },
    {
     "start": 3.53,
     "end": 5.55,
     "text": "The balance updates itself."
    }
   ],
   "words": [
    {
     "w": "receipts",
     "start": 0.5,
     "end": 0.94
    },
    {
     "w": "come",
     "start": 0.94,
     "end": 1.26
    },
    {
     "w": "in",
     "start": 1.26,
     "end": 1.5
    },
    {
     "w": "you",
     "start": 1.82,
     "end": 1.91
    },
    {
     "w": "approve",
     "start": 1.91,
     "end": 2.2
    },
    {
     "w": "them",
     "start": 2.2,
     "end": 2.39
    },
    {
     "w": "in",
     "start": 2.39,
     "end": 2.45
    },
    {
     "w": "one",
     "start": 2.45,
     "end": 2.69
    },
    {
     "w": "tap",
     "start": 2.69,
     "end": 3.03
    },
    {
     "w": "the",
     "start": 3.63,
     "end": 3.79
    },
    {
     "w": "balance",
     "start": 3.79,
     "end": 4.23
    },
    {
     "w": "updates",
     "start": 4.23,
     "end": 4.77
    },
    {
     "w": "itself",
     "start": 4.77,
     "end": 5.15
    }
   ]
  },
  "6": {
   "start": 42.45,
   "duration": 5.2,
   "cues": [
    {
     "start": 0.4,
     "end": 3.36,
     "text": "Your reps see exactly what they've earned."
    },
    {
     "start": 3.36,
     "end": 5.2,
     "text": "No more disputes."
    }
   ],
   "words": [
    {
     "w": "your",
     "start": 0.5,
     "end": 0.89
    },
    {
     "w": "reps",
     "start": 0.89,
     "end": 1.25
    },
    {
     "w": "see",
     "start": 1.25,
     "end": 1.41
    },
    {
     "w": "exactly",
     "start": 1.41,
     "end": 1.93
    },
    {
     "w": "what",
     "start": 1.93,
     "end": 2.19
    },
    {
     "w": "they've",
     "start": 2.19,
     "end": 2.46
    },
    {
     "w": "earned",
     "start": 2.46,
     "end": 3.02
    },
    {
     "w": "no",
     "start": 3.46,
     "end": 3.66
    },
    {
     "w": "more",
     "start": 3.66,
     "end": 3.89
    },
    {
     "w": "disputes",
     "start": 3.89,
     "end": 4.8
    }
   ]
  },
  "7": {
   "start": 47.65,
   "duration": 7.0,
   "cues": [
    {
     "start": 0.4,
     "end": 3.55,
     "text": "And buyers get a beautiful page to"
    },
    {
     "start": 3.55,
     "end": 7.0,
     "text": "explore estates and book inspections."
    }
   ],
   "words": [
    {
     "w": "and",
     "start": 0.5,
     "end": 0.81
    },
    {
     "w": "buyers",
     "start": 0.81,
     "end": 1.28
    },
    {
     "w": "get",
     "start": 1.28,
     "end": 1.71
    },
    {
     "w": "a",
     "start": 2.16,
     "end": 2.28
    },
    {
     "w": "beautiful",
     "start": 2.28,
     "end": 2.9
    },
    {
     "w": "page",
     "start": 2.9,
     "end": 3.43
    },
    {
     "w": "to",
     "start": 3.43,
     "end": 3.65
    },
    {
     "w": "explore",
     "start": 3.65,
     "end": 4.04
    },
    {
     "w": "estates",
     "start": 4.04,
     "end": 4.78
    },
    {
     "w": "and",
     "start": 4.78,
     "end": 5.07
    },
    {
     "w": "book",
     "start": 5.07,
     "end": 5.28
    },
    {
     "w": "inspections",
     "start": 5.7,
     "end": 6.78
    }
   ]
  },
  "8": {
   "start": 54.65,
   "duration": 14.0,
   "cues": [
    {
     "start": 0.4,
     "end": 2.16,
     "text": "Terratrail is live today."
    },
    {
     "start": 2.16,
     "end": 5.91,
     "text": "Landrite by GOE is our first paying customer."
    },
    {
     "start": 5.91,
     "end": 7.91,
     "text": "Lumina Properties is running a pilot."
    },
    {
     "start": 7.91,
     "end": 11.1,
     "text": "And Rehoboth Properties has committed to pay"
    },
    {
     "start": 11.1,
     "end": 14.0,
     "text": "once we ship the integration they asked for."
    }
   ],
   "words": [
    {
     "w": "terratrail",
     "start": 0.5,
     "end": 0.97
    },
    {
     "w": "is",
     "start": 0.97,
     "end": 1.16
    },
    {
     "w": "live",
     "start": 1.16,
     "end": 1.48
    },
    {
     "w": "today",
     "start": 1.48,
     "end": 1.95
    },
    {
     "w": "landrite",
     "start": 2.26,
     "end": 2.73
    },
    {
     "w": "by",
     "start": 2.73,
     "end": 2.87
    },
    {
     "w": "goe",
     "start": 2.87,
     "end": 3.24
    },
    {
     "w": "is",
     "start": 3.24,
     "end": 3.51
    },
    {
     "w": "our",
     "start": 3.51,
     "end": 3.63
    },
    {
     "w": "first",
     "start": 3.63,
     "end": 4.14
    },
    {
     "w": "paying",
     "start": 4.14,
     "end": 4.38
    },
    {
     "w": "customer",
     "start": 4.38,
     "end": 5.41
    },
    {
     "w": "lumina",
     "start": 6.01,
     "end": 6.39
    },
    {
     "w": "properties",
     "start": 6.39,
     "end": 6.97
    },
    {
     "w": "is",
     "start": 6.97,
     "end": 7.13
    },
    {
     "w": "running",
     "start": 7.13,
     "end": 7.45
    },
    {
     "w": "a",
     "start": 7.45,
     "end": 7.51
    },
    {
     "w": "pilot",
     "start": 7.51,
     "end": 8.01
    },
    {
     "w": "and",
     "start": 8.01,
     "end": 8.23
    },
    {
     "w": "rehoboth",
     "start": 8.23,
     "end": 8.8
    },
    {
     "w": "properties",
     "start": 8.8,
     "end": 9.42
    },
    {
     "w": "has",
     "start": 9.81,
     "end": 9.96
    },
    {
     "w": "committed",
     "start": 9.96,
     "end": 10.32
    },
    {
     "w": "to",
     "start": 10.32,
     "end": 10.4
    },
    {
     "w": "pay",
     "start": 10.4,
     "end": 10.75
    },
    {
     "w": "once",
     "start": 11.2,
     "end": 11.56
    },
    {
     "w": "we",
     "start": 11.56,
     "end": 11.79
    },
    {
     "w": "ship",
     "start": 11.79,
     "end": 12.33
    },
    {
     "w": "the",
     "start": 12.33,
     "end": 12.43
    },
    {
     "w": "integration",
     "start": 12.43,
     "end": 13.01
    },
    {
     "w": "they",
     "start": 13.01,
     "end": 13.15
    },
    {
     "w": "asked",
     "start": 13.15,
     "end": 13.48
    },
    {
     "w": "for",
     "start": 13.48,
     "end": 13.6
    }
   ]
  },
  "9": {
   "start": 68.65,
   "duration": 12.51,
   "cues": [
    {
     "start": 0.4,
     "end": 4.0,
     "text": "Over 5,000 companies have registered with REDAN,"
    },
    {
     "start": 4.0,
     "end": 7.19,
     "text": "Nigeria's association of real estate developers."
    },
    {
     "start": 7.19,
     "end": 8.67,
     "text": "And most of them still run their"
    },
    {
     "start": 8.67,
     "end": 12.51,
     "text": "sales on spreadsheets and WhatsApp."
    }
   ],
   "words": [
    {
     "w": "over",
     "start": 0.5,
     "end": 0.72
    },
    {
     "w": "five",
     "start": 0.72,
     "end": 0.99
    },
    {
     "w": "thousand",
     "start": 0.99,
     "end": 1.49
    },
    {
     "w": "companies",
     "start": 1.49,
     "end": 2.05
    },
    {
     "w": "have",
     "start": 2.05,
     "end": 2.52
    },
    {
     "w": "registered",
     "start": 2.52,
     "end": 3.09
    },
    {
     "w": "with",
     "start": 3.09,
     "end": 3.3
    },
    {
     "w": "redan",
     "start": 3.3,
     "end": 3.65
    },
    {
     "w": "nigeria's",
     "start": 4.1,
     "end": 4.77
    },
    {
     "w": "association",
     "start": 4.77,
     "end": 5.33
    },
    {
     "w": "of",
     "start": 5.33,
     "end": 5.5
    },
    {
     "w": "real",
     "start": 5.5,
     "end": 5.61
    },
    {
     "w": "estate",
     "start": 5.61,
     "end": 5.91
    },
    {
     "w": "developers",
     "start": 5.91,
     "end": 6.69
    },
    {
     "w": "and",
     "start": 7.29,
     "end": 7.46
    },
    {
     "w": "most",
     "start": 7.46,
     "end": 7.68
    },
    {
     "w": "of",
     "start": 7.68,
     "end": 7.8
    },
    {
     "w": "them",
     "start": 7.8,
     "end": 7.96
    },
    {
     "w": "still",
     "start": 7.96,
     "end": 8.49
    },
    {
     "w": "run",
     "start": 8.49,
     "end": 8.6
    },
    {
     "w": "their",
     "start": 8.6,
     "end": 8.77
    },
    {
     "w": "sales",
     "start": 8.77,
     "end": 9.59
    },
    {
     "w": "on",
     "start": 9.86,
     "end": 10.01
    },
    {
     "w": "spreadsheets",
     "start": 10.01,
     "end": 11.04
    },
    {
     "w": "and",
     "start": 11.49,
     "end": 11.67
    },
    {
     "w": "whatsapp",
     "start": 11.67,
     "end": 12.11
    }
   ]
  },
  "10": {
   "start": 81.16,
   "duration": 26.29,
   "cues": [
    {
     "start": 0.4,
     "end": 2.3,
     "text": "We're not new to this."
    },
    {
     "start": 2.3,
     "end": 5.05,
     "text": "We've worked on both sides of the problem,"
    },
    {
     "start": 5.05,
     "end": 9.0,
     "text": "as operations executives inside real estate"
    },
    {
     "start": 9.0,
     "end": 12.92,
     "text": "companies and as real estate investors ourselves."
    },
    {
     "start": 12.92,
     "end": 17.12,
     "text": "We've built products and a startup before."
    },
    {
     "start": 17.12,
     "end": 18.48,
     "text": "I'm the hustler."
    },
    {
     "start": 18.48,
     "end": 21.49,
     "text": "Demilade is the hacker."
    },
    {
     "start": 21.49,
     "end": 24.02,
     "text": "Sammy is the hipster."
    },
    {
     "start": 24.02,
     "end": 26.29,
     "text": "Together, we are Terratrail."
    }
   ],
   "words": [
    {
     "w": "we're",
     "start": 0.5,
     "end": 0.62
    },
    {
     "w": "not",
     "start": 0.62,
     "end": 0.83
    },
    {
     "w": "new",
     "start": 0.83,
     "end": 1.05
    },
    {
     "w": "to",
     "start": 1.05,
     "end": 1.19
    },
    {
     "w": "this",
     "start": 1.19,
     "end": 1.8
    },
    {
     "w": "we've",
     "start": 2.4,
     "end": 2.74
    },
    {
     "w": "worked",
     "start": 2.74,
     "end": 3.03
    },
    {
     "w": "on",
     "start": 3.03,
     "end": 3.3
    },
    {
     "w": "both",
     "start": 3.3,
     "end": 3.57
    },
    {
     "w": "sides",
     "start": 3.57,
     "end": 4.03
    },
    {
     "w": "of",
     "start": 4.03,
     "end": 4.15
    },
    {
     "w": "the",
     "start": 4.15,
     "end": 4.22
    },
    {
     "w": "problem",
     "start": 4.22,
     "end": 4.7
    },
    {
     "w": "as",
     "start": 5.15,
     "end": 5.69
    },
    {
     "w": "operations",
     "start": 5.79,
     "end": 6.27
    },
    {
     "w": "executives",
     "start": 6.27,
     "end": 7.22
    },
    {
     "w": "inside",
     "start": 7.67,
     "end": 8.61
    },
    {
     "w": "real",
     "start": 8.61,
     "end": 8.76
    },
    {
     "w": "estate",
     "start": 8.76,
     "end": 9.1
    },
    {
     "w": "companies",
     "start": 9.1,
     "end": 10.16
    },
    {
     "w": "and",
     "start": 10.16,
     "end": 10.27
    },
    {
     "w": "as",
     "start": 10.27,
     "end": 10.69
    },
    {
     "w": "real",
     "start": 10.81,
     "end": 10.92
    },
    {
     "w": "estate",
     "start": 10.92,
     "end": 11.26
    },
    {
     "w": "investors",
     "start": 11.26,
     "end": 11.8
    },
    {
     "w": "ourselves",
     "start": 11.8,
     "end": 12.42
    },
    {
     "w": "we've",
     "start": 13.02,
     "end": 13.5
    },
    {
     "w": "built",
     "start": 13.5,
     "end": 14.9
    },
    {
     "w": "products",
     "start": 14.9,
     "end": 15.62
    },
    {
     "w": "and",
     "start": 16.07,
     "end": 16.23
    },
    {
     "w": "a",
     "start": 16.23,
     "end": 16.35
    },
    {
     "w": "startup",
     "start": 16.55,
     "end": 16.92
    },
    {
     "w": "before",
     "start": 16.92,
     "end": 17.22
    },
    {
     "w": "i'm",
     "start": 17.22,
     "end": 17.31
    },
    {
     "w": "the",
     "start": 17.31,
     "end": 17.43
    },
    {
     "w": "hustler",
     "start": 17.43,
     "end": 17.98
    },
    {
     "w": "demilade",
     "start": 18.58,
     "end": 19.41
    },
    {
     "w": "is",
     "start": 19.86,
     "end": 20.06
    },
    {
     "w": "the",
     "start": 20.06,
     "end": 20.51
    },
    {
     "w": "hacker",
     "start": 20.51,
     "end": 20.99
    },
    {
     "w": "sammy",
     "start": 21.59,
     "end": 22.47
    },
    {
     "w": "is",
     "start": 22.73,
     "end": 22.87
    },
    {
     "w": "the",
     "start": 22.87,
     "end": 22.97
    },
    {
     "w": "hipster",
     "start": 22.97,
     "end": 23.52
    },
    {
     "w": "together",
     "start": 24.12,
     "end": 24.66
    },
    {
     "w": "we",
     "start": 25.11,
     "end": 25.29
    },
    {
     "w": "are",
     "start": 25.29,
     "end": 25.47
    },
    {
     "w": "terratrail",
     "start": 25.47,
     "end": 26.14
    }
   ]
  },
  "11": {
   "start": 107.45,
   "duration": 23.45,
   "cues": [
    {
     "start": 0.36,
     "end": 4.85,
     "text": "With this grant, we'll do three things."
    },
    {
     "start": 4.85,
     "end": 6.12,
     "text": "First, ship the integrations our"
    },
    {
     "start": 6.12,
     "end": 8.99,
     "text": "customers are already asking for."
    },
    {
     "start": 8.99,
     "end": 12.43,
     "text": "Second, build an AI layer that gives business owners"
    },
    {
     "start": 12.43,
     "end": 15.12,
     "text": "intelligence just by chatting with their data."
    },
    {
     "start": 15.12,
     "end": 19.67,
     "text": "And third, bring Terratrail to 30 real estate companies,"
    },
    {
     "start": 19.67,
     "end": 23.45,
     "text": "helping them recover payments and saving them hours."
    }
   ],
   "words": [
    {
     "w": "with",
     "start": 0.46,
     "end": 0.55
    },
    {
     "w": "this",
     "start": 0.55,
     "end": 0.91
    },
    {
     "w": "grant",
     "start": 0.91,
     "end": 2.48
    },
    {
     "w": "we'll",
     "start": 2.48,
     "end": 2.69
    },
    {
     "w": "do",
     "start": 2.69,
     "end": 3.16
    },
    {
     "w": "three",
     "start": 3.61,
     "end": 3.82
    },
    {
     "w": "things",
     "start": 3.82,
     "end": 4.35
    },
    {
     "w": "first",
     "start": 4.95,
     "end": 5.07
    },
    {
     "w": "ship",
     "start": 5.07,
     "end": 5.23
    },
    {
     "w": "the",
     "start": 5.23,
     "end": 5.33
    },
    {
     "w": "integrations",
     "start": 5.33,
     "end": 6.07
    },
    {
     "w": "our",
     "start": 6.07,
     "end": 6.22
    },
    {
     "w": "customers",
     "start": 6.22,
     "end": 6.76
    },
    {
     "w": "are",
     "start": 6.76,
     "end": 6.98
    },
    {
     "w": "already",
     "start": 7.43,
     "end": 7.76
    },
    {
     "w": "asking",
     "start": 8.21,
     "end": 8.62
    },
    {
     "w": "for",
     "start": 8.62,
     "end": 8.75
    },
    {
     "w": "second",
     "start": 9.09,
     "end": 9.32
    },
    {
     "w": "build",
     "start": 9.32,
     "end": 9.48
    },
    {
     "w": "an",
     "start": 9.48,
     "end": 9.55
    },
    {
     "w": "ai",
     "start": 9.55,
     "end": 9.68
    },
    {
     "w": "layer",
     "start": 9.68,
     "end": 10.1
    },
    {
     "w": "that",
     "start": 10.4,
     "end": 10.74
    },
    {
     "w": "gives",
     "start": 10.74,
     "end": 11.15
    },
    {
     "w": "business",
     "start": 11.6,
     "end": 11.99
    },
    {
     "w": "owners",
     "start": 11.99,
     "end": 12.53
    },
    {
     "w": "intelligence",
     "start": 12.53,
     "end": 12.98
    },
    {
     "w": "just",
     "start": 12.98,
     "end": 13.31
    },
    {
     "w": "by",
     "start": 13.31,
     "end": 13.58
    },
    {
     "w": "chatting",
     "start": 13.58,
     "end": 14.1
    },
    {
     "w": "with",
     "start": 14.1,
     "end": 14.23
    },
    {
     "w": "their",
     "start": 14.23,
     "end": 14.39
    },
    {
     "w": "data",
     "start": 14.39,
     "end": 14.62
    },
    {
     "w": "and",
     "start": 15.22,
     "end": 15.35
    },
    {
     "w": "third",
     "start": 15.35,
     "end": 16.58
    },
    {
     "w": "bring",
     "start": 16.58,
     "end": 16.78
    },
    {
     "w": "terratrail",
     "start": 16.78,
     "end": 17.41
    },
    {
     "w": "to",
     "start": 17.41,
     "end": 17.82
    },
    {
     "w": "thirty",
     "start": 18.27,
     "end": 18.83
    },
    {
     "w": "real",
     "start": 18.83,
     "end": 19.01
    },
    {
     "w": "estate",
     "start": 19.01,
     "end": 19.31
    },
    {
     "w": "companies",
     "start": 19.31,
     "end": 19.77
    },
    {
     "w": "helping",
     "start": 19.77,
     "end": 20.03
    },
    {
     "w": "them",
     "start": 20.03,
     "end": 20.23
    },
    {
     "w": "recover",
     "start": 20.23,
     "end": 20.66
    },
    {
     "w": "payments",
     "start": 20.66,
     "end": 21.32
    },
    {
     "w": "and",
     "start": 21.32,
     "end": 21.63
    },
    {
     "w": "saving",
     "start": 21.63,
     "end": 22.0
    },
    {
     "w": "them",
     "start": 22.0,
     "end": 22.16
    },
    {
     "w": "hours",
     "start": 22.36,
     "end": 23.05
    }
   ]
  },
  "12": {
   "start": 130.9,
   "duration": 9.77,
   "cues": [],
   "words": [
    {
     "w": "no",
     "start": 1.3,
     "end": 1.53
    },
    {
     "w": "spreadsheet",
     "start": 1.53,
     "end": 2.49
    },
    {
     "w": "no",
     "start": 2.59,
     "end": 2.87
    },
    {
     "w": "whatsapp",
     "start": 2.87,
     "end": 3.61
    },
    {
     "w": "no",
     "start": 4.06,
     "end": 4.24
    },
    {
     "w": "wahala",
     "start": 4.24,
     "end": 4.77
    }
   ]
  }
 }
};
